server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  tracing:
    sampling:
      probability: 1.0


spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**  #when we call api localhost:8060/employee/anything then it should redirect all traffic to employee-service
          filters:
            - AuthenticationFilter   #filter package's class from api-gateway

        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**
          filters:
            - AuthenticationFilter

        - id: security-service
          uri: lb://security-service
          predicates:
            -path: /auth/**  #RequestMapping
