spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: Ra9841754305!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  application:
    name: employee-service

  config:
    import: "optional:configserver:http://localhost:8088"
